### ISSUE TITLE
Inaccessible Host Error

### ISSUE THREAD

**Issue by ibjhb** [serg-io/backbone-dynamodb#7]
I consistently am getting the following error:
'Inaccessible host: `dynamodb.undefined.amazonaws.com\'. This service may not be available in the `us-east-1\' region.'

Even though I am setting:
Backbone.DynamoDB.config.update({ region: 'us-east-1' });

**Comment by ibjhb** [comment]
@serg-io I know you are usually busy but any update on this issue?  Thanks!

**Comment by serg-io** [comment]
@ibjhb, thanks for reporting this bug and sorry for the late reply.

I stopped using `config,update` a while ago (I've been using environment variables) and I'm not sure when it stopped working.

I just published version 1.0.1 (which includes a fix for this bug) to npm. Please switch to version 1.0.1. I also made a similar change to my other library: [dynamodb-atomic-counter](https://www.npmjs.com/package/dynamodb-atomic-counter). If you're also using that library, please upgrade to the latest version.

Let me know if you're still having problems.

**Comment by ibjhb** [comment]
I _really_ appreciate the quick update.  I'll test this out and let you know but reading through the code, I think it's going to work.
